### ISSUE TITLE
Problem to installing the extension on VSCode

### ISSUE THREAD

**Issue by kaburelabs** [monishski/plotly-dash-snippets#1]
Hey, I will open this issue just to officially start it =D

I tried to install it on my VSCode using a ubuntu 18.04 LTS but it's raising an error caused by my VSCode version. 

I would like to know how do I manage it to work? I have never had this problem before. 

![image](https://user-images.githubusercontent.com/24701735/106076573-97c9cd80-60ee-11eb-8793-c9391e6a7280.png)

**Comment by monishski** [comment]
Hi Leonardo, 

Thanks for your help!

It looks like the plugin requires VS code version **1.52.0** at least.
You could try to update VS code in the meantime. I will look to update the package.json file to accommodate for older versions of VS code.

**Comment by kaburelabs** [comment]
Hey @monishski it worked bro, thanks!!

![image](https://user-images.githubusercontent.com/24701735/106165351-cb960900-6169-11eb-9597-9c2552d4e2b5.png)

**Comment by monishski** [comment]
Great ;)
